TYPE=VIEW
query=select `northwind`.`customers`.`City` AS `City`,`northwind`.`customers`.`CompanyName` AS `CompanyName`,`northwind`.`customers`.`ContactName` AS `ContactName`,\'Customers\' AS `Relationship` from `northwind`.`customers` union select `northwind`.`suppliers`.`City` AS `City`,`northwind`.`suppliers`.`CompanyName` AS `CompanyName`,`northwind`.`suppliers`.`ContactName` AS `ContactName`,\'Suppliers\' AS `Suppliers` from `northwind`.`suppliers` order by `City`,`CompanyName`
md5=6f50a508d28c81f831baba938e058c62
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2018-04-09 13:28:15
create-version=2
source=SELECT City, \n       CompanyName, \n       ContactName, \n       \'Customers\' AS Relationship \nFROM Customers\nUNION \nSELECT City, \n       CompanyName, \n       ContactName, \n       \'Suppliers\'\nFROM Suppliers \nORDER BY City, CompanyName
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `northwind`.`customers`.`City` AS `City`,`northwind`.`customers`.`CompanyName` AS `CompanyName`,`northwind`.`customers`.`ContactName` AS `ContactName`,\'Customers\' AS `Relationship` from `northwind`.`customers` union select `northwind`.`suppliers`.`City` AS `City`,`northwind`.`suppliers`.`CompanyName` AS `CompanyName`,`northwind`.`suppliers`.`ContactName` AS `ContactName`,\'Suppliers\' AS `Suppliers` from `northwind`.`suppliers` order by `City`,`CompanyName`
mariadb-version=100128
